version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:3000"
    volumes:
      - .:/app
    environment:
      NODE_ENV: development
    env_file:
      - .env