# Name of this action
name: Jest Automatic Testing

# Event triggers on pull request event
on:
  push:
  pull_request:
  workflow_run:
    workflows: ['MySQL Workflow']
    types:
      - completed

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# The jobs this action will run.
jobs:
  # ID of the job
  run-jest-tests:
    # Name of the job as it will be displayed in GitHub
    name: Jest Tests
    # Machine which this action will be run on.
    runs-on: ubuntu-latest
    needs: [MySQL Workflow.sqlDatabaseSetup]  # Adjusted to reference the external job
      
    steps: 
      - name: Wait for SQL Database Setup
          run: echo "Waiting for SQL Database Setup to complete"
          if: needs.sqlDatabaseSetup.outputs.job_completed == 'true'

      - name: Checkout under $GITHUB_WORKSPACE
        uses: actions/checkout@v2
        with:
          ref: yzgithubaction

      - name: Set up NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: '20' # Ensure the correct Node.js version is specified

      - name: Install all dependencies
        run: npm install
        working-directory: backend

      - name: Run User Tests
        run: npm run test:user
        working-directory: backend

      - name: Run Session Tests
        run: npm run test:session
        working-directory: backend
    

