# Name of this action
name: API Automatic Testing

# Event triggers on pull request event
on:
  push:
  pull_request:
  workflow_run:
    workflows: [sqlDatabaseSetup]
    types:
      - completed

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# The jobs this action will run.
jobs:
  # ID of the job
  run-api-tests:
    # Name of the job as it will be displayed in GitHub
    name: Api Tests
    # Machine which this action will be run on.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout under $GITHUB_WORKSPACE
        uses: actions/checkout@v2
        with:
          ref: yzgithubaction

      - name: Set up NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: '20' # Ensure the correct Node.js version is specified

      - name: Install all dependencies
        run: npm install
        working-directory: backend

      - name: Run Test User
        run: npm run test:user
        working-directory: backend

      - name: Run Test Session
        run: npm run test:session
        working-directory: backend



    
