# Name of this action
name: Jest Automatic Testing

# Event triggers on pull request event
on:
  workflow_run:
    workflows: [sqlDatabaseSetup]
    types:
      - completed

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# The jobs this action will run.
jobs:
 # A placeholder job with no dependencies
  placeholder:
    name: Placeholder Job
    runs-on: ubuntu-latest
    steps:
      - name: Placeholder Step
        run: echo "This is a placeholder job with no dependencies"

  # ID of the job
  run-jest-tests:
    # Name of the job as it will be displayed in GitHub
    name: Jest Tests
    # Machine which this action will be run on.
    runs-on: ubuntu-latest
    steps:
      - name: Wait for SQL Database Setup
        run: echo "Waiting for SQL Database Setup to complete"
        # Wait for the completion of sqlDatabaseSetup job from sqlworkflow.yml
        # Access the output from sqlDatabaseSetup job using jobs.sqlDatabaseSetup.outputs.<output_name>
        # In this case, the output is the completion of the job itself, so we use jobs.sqlDatabaseSetup.outputs.job_completed
        if: needs.sqlDatabaseSetup.outputs.job_completed == 'true'
        
      - name: Checkout under $GITHUB_WORKSPACE
        uses: actions/checkout@v2
        with:
          ref: yzgithubaction

      - name: Set up NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: '14' # Ensure the correct Node.js version is specified

      - name: Install all dependencies
        run: npm install
        working-directory: backend

      - name: Run Jest Tests
        run: npm run test
        working-directory: backend

    
