name: Build and Deploy Backend Docker Images

on:
  pull_request:
    branches:
      - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Check out repository
              uses: actions/checkout@v2
            
            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                node-version: '20.11.0'
        
            # - name: Install Backend dependencies
            #   working-directory: ./backend
            #   run: npm install
            #

            - name: Create .env file
              run: |
                echo "MYSQL_HOST=${{ secrets.MYSQL_HOST }}"> backend/.env
                echo "MYSQL_USER=${{ secrets.MYSQL_USER }}" >> backend/.env
                echo "MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}" >> backend/.env
                echo "MYSQL_PORT=${{ secrets.MYSQL_PORT }}" >> backend/.env
                echo "MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }}" >> backend/.env
                echo "JWT_SECRET"="" >> backend/.env
            
            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PAT}}
            
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            # - name: Build and Push Docker Image
            #   uses: docker/build-push-action@v5
            #   with:
            #     context: ./backend
            #     file: ./backend/Dockerfile
            #     push: true
            #     tags: ${{ secrets.DOCKERHUB_USERNAME }}/

            