name: Build and Deploy Frontend Docker Image

# on:
#     pull_request:
#         types: [closed]
#         branches:
#             - main

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
    
        steps: 
            - name: Check out repository
              uses: actions/checkout@v2
            
            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                node-version: '20.11.0'

            - name: Create .env file
              run: |
                echo "REACT_APP_SERVER_URL_PROD=http://46.137.223.232:8080">> frontend/.env
            
            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PAT }}

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Build and Push Docker Image
              uses: docker/build-push-action@v5
              with:
                context: ./frontend
                file: ./frontend/Dockerfile
                push: true
                tags: ${{ secrets.DOCKER_USERNAME }}/sg_learner_client:latest

            - name: SSH into EC2 Deployment
              uses: appleboy/ssh-action@master
              with:
                host: ${{ secrets.EC2_CLIENT_HOST }}
                username: ${{ secrets.EC2_USERNAME }}
                key: ${{ secrets.EC2_CLIENT_KEY }}
                script: |
                  docker pull ${{ secrets.DOCKER_USERNAME }}/sg_learner_client:latest
                  docker stop sg_learner_client || true
                  docker rm sg_learner_client || true
                  docker run -d --name sg_learner_client -p 3000:3000 ${{ secrets.DOCKER_USERNAME }}/sg_learner_client:latest
                  docker image prune -a --force