name: Build

on:
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
    
        steps: 
            - name: Check out repository
              uses: actions/checkout@v2
            
            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                node-version: '20.11.0'
            
            - name: Install Frontend dependencies
              working-directory: ./frontend
              run: npm-install