name: Continous Integration Pipeline

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with: 
        node-version: '20.11.0'
    
    - name: Install dependencies
      working-directory: ./backend
      run: npm install

    - name: Create .env file
      run: |
        echo "MYSQL_HOST=sg-learner-db.c32qkcwscdls.ap-southeast-1.rds.amazonaws.com" > backend/.env
        echo "MYSQL_USER=admin" >> backend/.env
        echo "MYSQL_PASSWORD=password123" >> backend/.env
        echo "MYSQL_PORT=3306" >> backend/.env
        echo "MYSQL_DATABASE=sg_learner_db" >> backend/.env
        echo "JWT_SECRET"="" >> backend/.env

    - name: Check IP Address
      run: curl https://api.ipify.org
    