name: Continous Integration Pipeline

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        env: 
          MYSQL_ROOT_PASSWORD: rootpassword
          MYSQL_DATABASE: 'sg_learner_db'
          MYSQL_USER: 'yijie'
          MYSQL_PASSWORD: 'newpassword'
          MYSQL_HOST: 'localhost'
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with: 
        node-version: '20.11.0'
    
    - name: Install dependencies
      working-directory: ./backend
      run: npm install

    - name: Create .env file
      run: |
        echo "MYSQL_HOST=${{ secrets.MYSQL_HOST }}" > backend/.env
        echo "MYSQL_USER=${{ secrets.MYSQL_USER }}" >> backend/.env
        echo "MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}" >> backend/.env
        echo "MYSQL_PORT=${{ secrets.MYSQL_PORT }}" >> backend/.env
        echo "MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }}" >> backend/.env
    
    - name: Install MySQL client
      run: sudo apt-get install -y mysql-client

    - name: Create tables
      run : |
        mysql -h 127.0.0.1 -P 3306 -u yijie -p'newpassword' sg_learner_db -e 'CREATE TABLE `tbl_User` (
            `userID` INT NOT NULL AUTO_INCREMENT,
            `age` INT NOT NULL,
            `dateJoined` DATETIME DEFAULT NULL,
            `firstName` VARCHAR(25) NOT NULL,
            `lastName` VARCHAR(25) NOT NULL,
            `email` VARCHAR(25) NOT NULL,
            `education` VARCHAR(100) NOT NULL,
            `username` VARCHAR(255) UNIQUE NOT NULL,
            `password` VARCHAR(255) NOT NULL,
            `birthDate` DATETIME DEFAULT NULL,
            `gender` VARCHAR(1) NOT NULL,
            PRIMARY KEY (`userID`)
        );'    
    




